spring:
  application:
    name: zhihu_server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhihu_server
    username: root
    password: xmfaly
    test-while-idle: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    mongodb:
      host: 127.0.0.1
      database: zhihu_server
      port: 27017
jackson:
  serialization:
    INDENT_OUTPUT: true
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800